---
settings:
  name: BlueXP remediation
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de la reparación de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre la corrección de BlueXP
      url: "/concept-resource-templates.html"
    - title: Más información sobre etiquetado
      url: "/concept-tagging.html"
  - title: Utiliza la corrección de BlueXP
    entries:
    - title: Utilizar plantillas para estandarizar la creación de recursos
      entries:
      - title: Cree plantillas para su organización
        url: "/task-define-templates.html"
      - title: Comprobar los recursos para garantizar el cumplimiento de las plantillas
        url: "/task-check-template-compliance.html"
      - title: Ejecute plantillas para crear recursos
        url: "/task-run-templates.html"
    - title: Organice sus recursos con etiquetas
      entries:
      - title: Gestione etiquetas para sus recursos
        url: "/task-using-tags.html"
  - title: Conceptos
    entries:
    - title: Bloques de creación de plantillas
      url: "/reference-template-building-blocks.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
